name: Build CI Image

on:
    workflow_dispatch:
    push:
        branches:
            - dev
        paths:
            - .github/Dockerfile.ci

jobs:
    build:
        name: Build and push anchor-build image
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .github
                  file: .github/Dockerfile.ci
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/anchor-build:0.31.1
